language: python

python:
    - "3.7"
    - "3.8"

install:
    - pip install -r requirements.txt

before_install:
    - pip install pycodestyle

script:
    # Run pycodestyle on all .py files in all subfolders.
    # Ignore minor annoying errors.
    - find . -name \*.py -exec pycodestyle --ignore=E202,E203,E221,E221,E231,E241,E251,E272,E402,E501 {} +
